#define MIN_BMPID               1   /* Min resource ID for bitmpas */
#define MAX_BMPID              66   /* Max resource ID for bitmaps */

#define ID_ACTION_MIN          100  /* First ACTION ID */

#define ID_ACTION_FILE           100
#define ID_ACTION_NEW            101
#define ID_ACTION_OPEN           102
#define ID_ACTION_SAVE           103
#define ID_ACTION_CLOSE          104
#define ID_ACTION_EDIT           105
#define ID_ACTION_COPY           106
#define ID_ACTION_CUT            107
#define ID_ACTION_PASTE          108
#define ID_ACTION_UNDO           109
#define ID_ACTION_LINK           110
#define ID_ACTION_SELECTALL      111
#define ID_ACTION_DESELECTALL    112
#define ID_ACTION_VIEW           113
#define ID_ACTION_VIEWCMD        114
#define ID_ACTION_VIEWTOOL       115
#define ID_ACTION_VIEWCOLOR      116
#define ID_ACTION_VIEWDISK       117
#define ID_ACTION_ZOOMIN         118
#define ID_ACTION_ZOOMOUT        119
#define ID_ACTION_STYLES         120
#define ID_ACTION_BOLD           121
#define ID_ACTION_ITALIC         122
#define ID_ACTION_UNDERLINE      123

#define ID_ACTION_TOOLS          130
#define ID_ACTION_TOOLSLCT       131
#define ID_ACTION_TOOLDRAW       132
#define ID_ACTION_TOOLBRSH       133
#define ID_ACTION_TOOLERAS       134
#define ID_ACTION_TOOLSPRY       135
#define ID_ACTION_TOOLFILL       136
#define ID_ACTION_TOOLLINE       137
#define ID_ACTION_TOOLARC        138
#define ID_ACTION_TOOLRECT       139
#define ID_ACTION_TOOLCIRC       140
#define ID_ACTION_TOOLTEXT       141
#define ID_ACTION_TOOLLSEG       142
#define ID_ACTION_TOOLCURV       143
#define ID_ACTION_TOOLSHP        144
 
#define ID_ACTION_COLORS         160
#define ID_ACTION_PALETTE        161
#define ID_ACTION_BLACK          162
#define ID_ACTION_DGRAY          163
#define ID_ACTION_PGRAY          164
#define ID_ACTION_PPINK          165
#define ID_ACTION_DBLUE          166
#define ID_ACTION_BLUE           167
#define ID_ACTION_MBLUE          168
#define ID_ACTION_DCYAN          169
#define ID_ACTION_CYAN           170
#define ID_ACTION_DGREEN         171
#define ID_ACTION_MGREEN         172
#define ID_ACTION_GREEN          173
#define ID_ACTION_DRED           174
#define ID_ACTION_MRED           175
#define ID_ACTION_RED            176
#define ID_ACTION_ORANGE         177
#define ID_ACTION_DPINK          178
#define ID_ACTION_PINK           179
#define ID_ACTION_BROWN          180
#define ID_ACTION_YELLOW         181
#define ID_ACTION_WHITE          182
#define ID_ACTION_OPTIONS        183
#define ID_ACTION_FONTS          184
#define ID_ACTION_GRID           185
#define ID_ACTION_RULER          186
#define ID_ACTION_MAG            187
 
#define ID_ACTION_DISKS          200
#define ID_ACTION_DISKA          201
#define ID_ACTION_DISKB          202
#define ID_ACTION_DISKC          203
#define ID_ACTION_DISKD          204
 
#define ID_ACTION_HELP           220
#define ID_ACTION_USINGHELP      221
#define ID_ACTION_ABOUT          222

#define ID_ACTION_MAX          299  /* Last ACTION ID */

#define ID_FRAME_RESOURCE      700 
#define ID_COMMANDBAR          701
#define ID_TOOLBAR             702
#define ID_COLORBAR            703
#define ID_DISKBAR             704
#define ID_GALORE_BITMAP       705
